### ISSUE TITLE
Add an option to improve Radarr support with nyaa.si tracker

### ISSUE THREAD

**Issue by Atakku** [Prowlarr/Prowlarr#1653]
### Is there an existing issue for this?

- [X] I have searched the existing open and closed issues

### Is your feature request related to a problem? Please describe

nyaa.si has an option to improve compatibility with Sonarr already. I think it would benefit to add a Radarr specific compatibility improvement too.

### Describe the solution you'd like

 nyaa.si, and generally all other Anime torrent's I've seen do not specify year in the movie title. You can filter out the year in Radarr's tracker settings, which makes it work but only half way. Radarr does not accept results without a year, even if the title fully matches (Because the parser gives up entirely if it can't find the year). What would be amazing is for Prowlarr to filter out the year when querying nyaa.si, but apply it back on results reseived back from nyaa.si (and possibly other trackers), patching the year into the movie titles, to finally fix this painful problem

### Describe alternatives you've considered

Alternatives are filtering the year on Radarr's side, but then it still doesn't work, and you can only manually approve the results. The catch is that because it completely gives up on parsing, you don't get any useful insight on priority score, because its never calculated. So the whole point of setting up radarr with custom formats ends up for nothing.

### Anything else?

Here is a screenshot I guess.
![image](https://github.com/Prowlarr/Prowlarr/assets/57140941/267d76b2-4cde-4775-b16d-36d3afcd64ff)
Links to similar issues reported by people:
https://www.reddit.com/r/radarr/comments/as4rid/cant_find_anime/
https://www.reddit.com/r/radarr/comments/ytdzja/trying_to_use_radarr_for_anime_movies_but_i_am/

**Comment by Atakku** [comment]
> Sadly this is not a job for Prowlarr to do. For Sonarr we're simply adding `S01` when there is no season/episode, but we can't add the exact year of the release from thin air for movies.
> 
> Feel free to fill a report directly to Radarr, maybe there's something to be done to the title parser.

No, radarr is already sending you the year, you just need to strip it when sending to nyaa.si, and inject it back into results from nyaa.si when sending to radarr.

**Comment by Atakku** [comment]
You can add the year before the first [ which would fix most if not all releases. You can also try to find what Radarr asked for (with year removed) in the name, and put year directly after that.

So you could have prowlarr try to match the requested title first and add the year, then if the title not found, try to add it before the first [, and then if all of that fails, just put the year at the very end

**Comment by bakerboy448** [comment]
- adding the year at the very end will never work and shouldn't even be bothered with
- Adding the year before the first [ would mean prepending it prior to the group which will likely not work either
- The Radarr parser requires the year after the movie title, that's something unlikely to change in Radarr anytime soon.

the only feasible options would be

- [ ] striping the year from the search and appending after the second [ if there is more than 1
- [ ] Stripping the year from the search and appending after the term radarr searched

**Comment by bakerboy448** [comment]
Does the file name have the year in the title? If not then all you're fixing is the grab and imports will be manual anyway? @Atakku 

of note Nyaa devs hate automation and think it is pointless and permabann IPs if you breech a small arbitrary search limit.

If anime release groups followed any standard at all this would be a moot point but instead they decide per release how to name things with near 0 consistency
