### ISSUE TITLE
Updates Todo

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Prowlarr#46]
- [x]  Labels [Update in Bulk Link](https://gist.github.com/bakerboy448/14ea471da15ff5f8c38d7260099ad028)
- [x] PR Templates - https://github.com/Prowlarr/Prowlarr/pull/49
- [x]  Issue Templates - https://github.com/Prowlarr/Prowlarr/pull/49
- [x] git Auto locking
- [x] git Support bot
- [ ] Various Links (site, sub, wiki, readme)
  - [ ] Discord
  - [ ] Wiki
  - [ ] Site
  - [ ] OC
- [x] Subreddit (Automod, Theme, AssistBot, Public)
- [x] Readme
- [x] Wiki
- [x] ~~Configure Servarr Bot ([Common])?~~ (Leaving it off)
